### ISSUE TITLE
Timeout on test suite with completed pod

### ISSUE THREAD

**Issue by adamwalach** [kyma-incubator/octopus#29]
**Description**

When I triggered tests for Kyma release 1.13rc0 the kyma-gke-integration job failed. It timed out on the ClusterTestSuite step. I see in the logs that last test "core-core-ui-acceptance" is still in progress, but the "oct-tp-testsuite-all-2019-07-04-10-32-test-core-core-ui-acceptance-0" pod is completed. 

**Expected result**

Test should be terminated when pod is "Completed"

**Actual result**

Test is pending but the corresponding pod is "Completed"

**Steps to reproduce**

It happened also in kyma-integration job https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/4746/pre-rel13-kyma-integration/1146721314044645376/build-log.txt

Kyma 1.3-RC0 PR: https://github.com/kyma-project/kyma/pull/4746

**Troubleshooting**

[1146720810015133697-pre-rel13-kyma-gke-integration.log](https://github.com/kyma-incubator/octopus/files/3359166/1146720810015133697-pre-rel13-kyma-gke-integration.log)
[testing-octopus-0.log](https://github.com/kyma-incubator/octopus/files/3359167/testing-octopus-0.log)
[testsuite-all-2019-07-04-10-32.log](https://github.com/kyma-incubator/octopus/files/3359168/testsuite-all-2019-07-04-10-32.log)
[pods.log](https://github.com/kyma-incubator/octopus/files/3359169/pods.log)

**Comment by adamwalach** [comment]
Problem solved.
The issue was caused by a missing docker image. The strange thing is that kubectl shows all pods as completed:
![pods](https://user-images.githubusercontent.com/8530211/60671929-866a0200-9e74-11e9-8498-5adbe2be0965.png)
But the `core-core-ui-acceptance-0` is in fact "pending".
![pending-pod](https://user-images.githubusercontent.com/8530211/60672100-d648c900-9e74-11e9-8c41-1a105a9f9327.png)

[pod-completed.log](https://github.com/kyma-incubator/octopus/files/3359587/pod-completed.log)

**Comment by aszecowka** [comment]
@adamwalach Let me reopen this issue: we can think if we can handle such a situation better from the Octopus perspective.

**Comment by sjanota** [comment]
I've seen it previously when we have added sidecars to tests. Even if the test fails its status is `Completed` in `kubectl get pods` output. It looks like it shows recently changed container status instead of pod status, which is more helpful in most cases. 

IMO the problem with octopus here is that it hasn't stopped the execution of the test with missing image. In the case when we cannot schedule a pod for some time, we can act in two ways:
1. Interrupt the whole suite. We don't know when the pod will get scheduled so it might kick in in the middle of the execution of the other test and break concurrency settings.
2. Just don't care, treat it like finished with error and start another test.

I'm leaning towards the first option as it's safer.

**Comment by sjanota** [comment]
Implementing #13 will solve the problem partially.

**Comment by pbochynski** [comment]
@sjanota Can you check if it is still valid, and close or label it properly?
