### ISSUE TITLE
Allow optional tests

### ISSUE THREAD

**Issue by k15r** [kyma-incubator/octopus#39]
**Description**

Sometimes tests are flaky. In this case they usually get disabled, means they do not get executed at all.
We should allow to mark a tests as `optional`. 
An `optional` test would be executed and even retried according to the `TestSuite` definition. But its result does not affect the `Testsuites` result. 

**Reasons**

A test can fail because of different reasons. 
- test is just broken => the correct thing to do is to disable it and fix it
- some other test has sideeffects on the test => disabling the one of the tests will 'fix' the failure, but also make it hard to figure out the actual reason for the failure

Here it would be useful to mark a test as `optional`. This way we could retrieve the test logs as if it would be enabled, but also do not break builds as it does not fail the testsuite.

**Attachments**

**Comment by aszecowka** [comment]
Hello @k15r, thanks for reporting the issue. IMO this is a good idea to extend TestDefinition with `optional` fields. Till we implement it, you can achieve similar functionality with the following approach:
- mark optional tests with some specific label, like `optional=true`
- create `ClusterTestSuite` with only `required` tests. You should set `matchLabelExpressions` to `optional != true` (you need to check it because I haven't tested it)
- create `ClusterTestSuite` with `optional=true`. 

Then wait for the completion of both `ClusterTestSuites`, but ignore result for optional tests.

**Comment by pbochynski** [comment]
The test should be fixed - it can be done on PR. Just run it 1000 times :-P before merge.
